version: '3.7'
services:
  discord:
    build: .
    command: yarn dev
    container_name: discord
    env_file: .env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres@postgres:5432/bot_dev
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/dist/
      - .:/usr/src/app

  postgres:
    image: postgres:12.2
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=bot_dev
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: